// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xycphqwgcbspmzekoczd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5Y3BocXdnY2JzcG16ZWtvY3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxODE0OTMsImV4cCI6MjA5MTc1NzQ5M30.wOe7MdROyw_kUjQ5ri7DXId9Y4ItFMVVdepnuiVzzcY";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);